# .github/actions/build-godot/action.yml
name: Build Godot
description: Build Godot with SCons (incremental, uses implicit cache).
inputs:
  target:
    description: The SCons target (debug/release_debug/release).
    default: "debug"
  tools:
    description: Build tools?
    default: false
  tests:
    description: Build tests?
    default: false
  platform:
    description: Godot platform (e.g. vita, android).
  sconsflags:
    description: Extra SCons flags.
    default: ""
  scons-cache:
    description: Path to SCons cache.
    default: "${{ github.workspace }}/.scons-cache/"
runs:
  using: "composite"
  steps:
    - name: SCons Build
      shell: bash
      env:
        # Tell SCons to use its implicit-dependency cache here:
        SCONS_CACHE: ${{ inputs.scons-cache }}
        # Pass implicit caching to SCons as well:
        SCONSFLAGS: "--implicit-cache ${{ inputs.sconsflags }}"
      run: |
        echo "Building with flags: $SCONSFLAGS"
        # Invoke SCons in the *same* workspace where the cache was restored
        scons p=${{ inputs.platform }} \
              target=${{ inputs.target }} \
              tools=${{ inputs.tools }} \
              tests=${{ inputs.tests }} \
              $SCONSFLAGS
        ls -l bin/
