# .github/actions/godot-deps/action.yml
name: Setup Python & SCons
description: Install Python and pinned SCons.
inputs:
  python-version:
    description: Semantic version (e.g. "3.x").
    default: "3.x"
  python-arch:
    description: "x64" or "x86".
    default: "x64"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        architecture: ${{ inputs.python-arch }}
    - name: Install SCons
      shell: bash
      run: |
        python -m pip install --upgrade scons==4.7.0
        scons --version
