name: "🎮 PSVita Builds"
on: [push, pull_request]

env:
  GODOT_BASE_BRANCH: 3.x
  SCONSFLAGS: "verbose=no warnings=no werror=no debug_symbols=no use_rtti=True disable_gles3=True disable_exceptions=yes"
  VITASDK: /usr/local/vitasdk
  VDPM_COMMIT: 426032a2fd05300cf9ef04e5f691f07f642c14cf
  VITA_PACKAGES_EXTRA_COMMIT: 6000b5630c3a7fc2fb368293dd35560bd2e72e0f
  SDK_URL: "https://github.com/vitasdk/autobuilds/releases/download/master-linux-v2.529/vitasdk-x86_64-linux-gnu-2025-03-11_15-12-52.tar.bz2"
  EUID: 1

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-vita
  cancel-in-progress: true

jobs:
  vita-template:
    runs-on: ubuntu-24.04
    name: Template (target=release, tools=no)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Setup VitaSDK
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y cmake libarchive-tools fakeroot zip git-core python3 make autoconf texinfo bison flex libtool
          
          # Set GitHub authentication to avoid rate limiting
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          
          # Clone and pin to stable commits
          git clone https://github.com/vitasdk/vdpm
          git clone https://github.com/isage/vita-packages-extra
          
          cd vdpm
          git checkout $VDPM_COMMIT
          
          # Use the -u flag to pin the exact SDK version
          ./bootstrap-vitasdk.sh -u "$SDK_URL"
          ./install-all.sh
          export PATH=$VITASDK/bin:$PATH
          ./vdpm -f vita-rss-libdl
          
          cd ../vita-packages-extra
          git checkout $VITA_PACKAGES_EXTRA_COMMIT
          cd pvr_psp2
          vita-makepkg
          ../../vdpm/vdpm *-arm.tar.xz

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: vita
          target: release
          tools: false

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: vita-template
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
